name: Terraform formatting and docs generation
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  formatting:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@10eaa13fa61437aa51be2d12fafe95f152e3512d
        with:
          path: .
  docs:
    needs: formatting
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs inside the docs/module.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          working-dir: .
          output-file: ./docs/module.md
          output-method: inject
          output-format: markdown table
          indention: 2
          git-push: "true"
